name: coffee_http
description: Easy http request
version: 0.0.1
author: Hadrien Lejard <hadrien.lejard@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  http: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  browser: any
  dogma_codegen: '>=0.0.2 <0.1.0'
  grinder: any
