name: coffee_http
description: Easy http request
version: 0.2.5
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/coffee_http

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  http: ">=0.11.3"
  convert: ">=1.1.1"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  browser: "^0.10.0+2"
  dogma_codegen: '>=0.0.2 <0.1.0'
  grinder: "^0.8.0+2"
