// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-04-25 21:42:11.367195

library models.example.convert.resource_model_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import '../models/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [ResourceModel].
class ResourceModelDecoder extends Converter<Map<dynamic, dynamic>, ResourceModel>
    implements ModelDecoder<ResourceModel> {
  @override
  ResourceModel create() => new ResourceModel();
  @override
  ResourceModel convert(Map input, [ResourceModel model]) {
    model ??= create();

    model.name = input['name'];
    model.capacity = input['capacity'];
    return model;
  }
}

/// A [ModelEncoder] for [ResourceModel].
class ResourceModelEncoder extends Converter<ResourceModel, Map<dynamic, dynamic>>
    implements ModelEncoder<ResourceModel> {
  @override
  Map convert(ResourceModel input) {
    var model = {};

    model['name'] = input.name;
    model['capacity'] = input.capacity;

    return model;
  }
}
